/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Fruits } from "./components/fruit-list/fruits.model";
export namespace Components {
    interface FruitList {
        "fruitsData": Fruits[] | string;
    }
    interface ListItem {
        "color": string;
        "fruit": string;
    }
}
declare global {
    interface HTMLFruitListElement extends Components.FruitList, HTMLStencilElement {
    }
    var HTMLFruitListElement: {
        prototype: HTMLFruitListElement;
        new (): HTMLFruitListElement;
    };
    interface HTMLListItemElement extends Components.ListItem, HTMLStencilElement {
    }
    var HTMLListItemElement: {
        prototype: HTMLListItemElement;
        new (): HTMLListItemElement;
    };
    interface HTMLElementTagNameMap {
        "fruit-list": HTMLFruitListElement;
        "list-item": HTMLListItemElement;
    }
}
declare namespace LocalJSX {
    interface FruitList {
        "fruitsData"?: Fruits[] | string;
    }
    interface ListItem {
        "color"?: string;
        "fruit"?: string;
    }
    interface IntrinsicElements {
        "fruit-list": FruitList;
        "list-item": ListItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fruit-list": LocalJSX.FruitList & JSXBase.HTMLAttributes<HTMLFruitListElement>;
            "list-item": LocalJSX.ListItem & JSXBase.HTMLAttributes<HTMLListItemElement>;
        }
    }
}
